"""init accesos + blacklist + tenant_id

Revision ID: 59193f850017
Revises: 
Create Date: 2026-09-24 13:35:36.228406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59193f850017'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('rol', sa.String(), nullable=True),
    sa.Column('recurso', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('hora', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('motivos', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accesos_ip'), 'accesos', ['ip'], unique=False)
    op.create_index(op.f('ix_accesos_tenant_id'), 'accesos', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_accesos_usuario'), 'accesos', ['usuario'], unique=False)
    op.create_table('blacklist',
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ip')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist')
    op.drop_index(op.f('ix_accesos_usuario'), table_name='accesos')
    op.drop_index(op.f('ix_accesos_tenant_id'), table_name='accesos')
    op.drop_index(op.f('ix_accesos_ip'), table_name='accesos')
    op.drop_table('accesos')
    # ### end Alembic commands ###
